### ISSUE TITLE
cannot find AMR parser.

### ISSUE THREAD

**Issue by exoskeletonzj** [RunxinXu/TSAR#1]
hi dear,
I cannot find AMRParser this module(attached picture1)  & donot know how to use this code block(attached picture 2).

appreciate for your reply.

![image](https://user-images.githubusercontent.com/33819727/170203974-1bfce25d-1321-4048-b418-c7f7dfc425d0.png)
![image](https://user-images.githubusercontent.com/33819727/170204029-b275ecdc-2fbf-4613-a29f-91de2d1f77c5.png)

**Comment by exoskeletonzj** [comment]
solved.

**Comment by kkkeepgoing** [comment]
> solved.

hi, I have the same problem, how did you solve it?
