### ISSUE TITLE
Error message about text.py not found in run.py file

### ISSUE THREAD

**Issue by marceio11** [RunxinXu/TSAR#12]

**Comment by xiehou-design** [comment]
I also met the problem, can you tell me how to solve it? Looking forward your reply.

**Comment by marceio11** [comment]
> I also met the problem, can you tell me how to solve it? Looking forward your reply.

I looked at the source function and found that the first variable input should be a file format, so I changed text.py to text and the model ran

**Comment by xiehou-design** [comment]
> > I also met the problem, can you tell me how to solve it? Looking forward your reply.
> 
> I looked at the source function and found that the first variable input should be a file format, so I changed text.py to text and the model ran

ok, thank you.

**Comment by marceio11** [comment]
不客气哒，很高兴能帮到你！

**Comment by marceio11** [comment]
> > > 我也遇到了这个问题，能告诉我怎么解决吗？期待你的回复。
> > 
> > 
> > 看了source函数，发现第一个变量input应该是文件格式，于是把text.py改成text，模型就跑了
> 
> 好的谢谢。

不客气哒，很高兴能帮到你！
