### ISSUE TITLE
Excuse me , what's the "text.py" in run.py lines 209 refers to ?

### ISSUE THREAD

**Issue by cathyry** [RunxinXu/TSAR#2]
When I run the code , I met with the error "ConnectionError: Couldn't reach https://raw.githubusercontent.com /huggingface /datasets /1.8.0/datasets/text.py/text.py" , so I wonder "text.py" is a local file or others ?

**Comment by RunxinXu** [comment]
Hi，it seems that the file cannot be downloaded automatically from huggingface in your device.
You can manually download it, and put it in the folder.
