### ISSUE TITLE
Missing 'text'.py in load_dataset in run.py

### ISSUE THREAD

**Issue by jefflink** [RunxinXu/TSAR#3]
I tried running the examples given but for the bash run_xx.sh which uses run.py, it fails in the following line 

```python:
datasets = load_dataset("text.py", data_files={'train': data_args.train_file,
                                                'validation': data_args.validation_file,
                                                'test': data_args.test_file})
```
Is there a missing text.py somewhere?

**Comment by cathyry** [comment]
I met the same trouble with you , and author told me :"Hi，it seems that the file cannot be downloaded automatically from huggingface in your device. You can manually download it, and put it in the folder." 
  However ,  this file couldn't be find in huggingface .

**Comment by jefflink** [comment]
@cathyry After looking through the code, I believed the author was using an old version of datasets and hence using some custom script. It can now be replaced with just the following:
```python:
datasets = load_dataset("text", data_files={'train': data_args.train_file,
                                                'validation': data_args.validation_file,
                                                'test': data_args.test_file})
```
I have tested and it seems to be running ok so far.

**Comment by cathyry** [comment]
> 

It works , thanks a lot.

**Comment by cathyry** [comment]
@jefflink It works , thanks a lot .
