### ISSUE TITLE
size mismatched when loading best saved model

### ISSUE THREAD

**Issue by jefflink** [RunxinXu/TSAR#4]
I was trying to load the best model from the trainer but I encounter that the size is mismatched and was not able to load the model.

```python
model = MyBertmodel.from_pretrained('./wikievents-base/checkpoint-22680')
```
The error I got was:
```python
RuntimeError: Error(s) in loading state_dict for MyBertmodel:
	size mismatch for middle_layer.0.weight: copying a param with shape torch.Size([768, 3840]) from checkpoint, the shape in current model is torch.Size([768, 3072]).
```
Am I loading it wrongly? or what's the correct way to load the best model again?

**Comment by RunxinXu** [comment]
Hi，have you modified the code? 
You just train the model and then reload the best model, right?

**Comment by jefflink** [comment]
Hi @RunxinXu,

Yes, I modified the code (changing the text.py to text) and trained it accordingly, after which checkpoint-22680 was the best model. I then tried to load back the model based on the code above and ran into that error. Did you also load back the model that way? If so, maybe there's something wrong with the model I trained and I will re-train it again.

**Comment by RunxinXu** [comment]
I did not try to reload the best model, since the result file generated by the best model would be saved, and the evaluation would be conducted based on this result file.
Maybe you could try to re-train it again~

**Comment by jefflink** [comment]
I finally found the error that I made. The checkpoint itself is insufficient, minimally the gcn_layer attribute has to be added as well, but to be safe, just add the rest of the attribute according to the code.
```python
 model = MyBertmodel.from_pretrained(
    "./wikievents-base/checkpoint-22680/",
    revision="main",
    config=config,
    gcn_layers=4,
    lambda_boundary=0.1,
    event_embedding_size=200,
)
```
